# 问询型参数 desc 口语化映射（发起人 2026-09-17 指令：对人不暴露参数名、说人话）。
# 格式：(skill_id, param_name) -> 新 desc（一句完整可答的话，含格式示例）。
# 只动 desc，不动 name/source/命令模板。跨同名义参数保持一致话术。
MAP = {
    # ---------- host ----------
    ("host.cpu.load-high", "load1"): "请输入期望的最高负载阈值（1 分钟均值，如 8）",
    ("host.memory.leak", "available_pct"): "请输入期望的最低可用内存百分比（如 10 表示低于 10% 时告警）",
    ("host.network-stack.dns-resolve-fail", "domain"): "请输入解析失败的域名（如 api.example.com）",
    ("host.process.dstate-hang", "pids"): "请输入卡住的进程号，多个用空格分隔（如 1234 5678）",
    ("host.process.fd-leak", "pid"): "请输入要检查的进程号（如 1234）",
    ("host.storage.fs-readonly", "device"): "请输入出问题的磁盘分区设备（如 /dev/sda1）",
    ("host.storage.fs-readonly", "mount"): "请输入需要排查的具体目录（格式如：/、/var、/data）",
    ("host.storage.capacity.disk-full", "mount"): "请输入需要排查的具体目录（格式如：/、/var、/data）",
    ("host.system.cert-expiry", "endpoint"): "请输入待检测的地址和端口（如 example.com:443）",
    ("host.system.cert-expiry", "days_left"): "请输入希望至少剩余的天数（如 30）",
    ("host.system.cert-expiry", "sni"): "请输入 TLS 握手使用的域名（默认与地址相同，可直接回车）",
    ("host.system.systemd-unit-failed", "unit"): "请输入失败的服务名（如 nginx.service）",
    # ---------- k8s ----------
    ("k8s.networking.dns-fail", "ns"): "请输入 Pod 所在的命名空间（如 default）",
    ("k8s.networking.dns-fail", "pod"): "请输入有问题的 Pod 名",
    ("k8s.networking.ingress-5xx", "ns"): "请输入命名空间（如 default）",
    ("k8s.networking.ingress-5xx", "svc"): "请输入后端 Service 名称",
    ("k8s.networking.networkpolicy-block", "ns"): "请输入命名空间（如 default）",
    ("k8s.networking.service-external-unreachable", "ns"): "请输入命名空间（如 default）",
    ("k8s.networking.service-external-unreachable", "svc"): "请输入 Service 名",
    ("k8s.networking.service-no-endpoints", "ns"): "请输入命名空间（如 default）",
    ("k8s.networking.service-no-endpoints", "svc"): "请输入 Service 名",
    ("k8s.networking.service-no-endpoints", "selector"): "请输入期望的标签选择器（如 app=web），不确定可直接回车",
    ("k8s.release.hpa-not-scaling", "ns"): "请输入命名空间（如 default）",
    ("k8s.release.hpa-not-scaling", "hpa"): "请输入弹性伸缩（HPA）名称",
    ("k8s.release.rollback", "ns"): "请输入命名空间（如 default）",
    ("k8s.release.rollback", "deploy"): "请输入要回滚的应用（Deployment）名",
    ("k8s.release.rollback", "target_revision"): "请输入要回到的版本号（如 3 表示第 3 次历史版本），不确定可直接回车",
    ("k8s.release.rollout-stuck", "ns"): "请输入命名空间（如 default）",
    ("k8s.release.rollout-stuck", "deploy"): "请输入发布卡住的应用（Deployment）名",
    ("k8s.resource.quota-exceeded", "ns"): "请输入命名空间（如 default）",
    ("k8s.scheduling.pending-unschedulable", "ns"): "请输入命名空间（如 default）",
    ("k8s.scheduling.pending-unschedulable", "pod"): "请输入一直 Pending 的 Pod 名",
    ("k8s.scheduling.taint-blocking", "ns"): "请输入命名空间（如 default）",
    ("k8s.storage.pvc-pending", "ns"): "请输入命名空间（如 default）",
    ("k8s.storage.pvc-pending", "pvc"): "请输入一直 Pending 的存储声明（PVC）名",
    ("k8s.storage.pvc-resize-stuck", "ns"): "请输入命名空间（如 default）",
    ("k8s.storage.pvc-terminating-stuck", "ns"): "请输入命名空间（如 default）",
    ("k8s.storage.volume-multiattach", "ns"): "请输入命名空间（如 default）",
    ("k8s.workload.configmap-not-applied", "ns"): "请输入命名空间（如 default）",
    ("k8s.workload.crashloop", "ns"): "请输入命名空间（如 default）",
    ("k8s.workload.crashloop", "pod"): "请输入反复重启的 Pod 名",
    ("k8s.workload.cronjob-not-running", "ns"): "请输入命名空间（如 default）",
    ("k8s.workload.cronjob-not-running", "name"): "请输入定时任务（CronJob）名",
    ("k8s.workload.image-pull-fail", "ns"): "请输入命名空间（如 default）",
    ("k8s.workload.image-pull-fail", "pod"): "请输入拉取镜像失败的 Pod 名",
    ("k8s.workload.image-pull-slow", "ns"): "请输入命名空间（如 default）",
    ("k8s.workload.init-container-stuck", "ns"): "请输入命名空间（如 default）",
    ("k8s.workload.init-container-stuck", "pod"): "请输入初始化容器卡住的 Pod 名",
    ("k8s.workload.liveness-restart-loop", "ns"): "请输入命名空间（如 default）",
    ("k8s.workload.oomkilled", "ns"): "请输入命名空间（如 default）",
    ("k8s.workload.oomkilled", "pod"): "请输入被杀（OOM）的 Pod 名",
    ("k8s.workload.readiness-probe-failing", "ns"): "请输入命名空间（如 default）",
    # ---------- middleware ----------
    ("middleware.kafka.consumer-lag", "broker"): "请输入 Kafka 服务地址（格式如 broker1:9092）",
    ("middleware.kafka.under-replicated", "broker"): "请输入 Kafka 服务地址（格式如 broker1:9092）",
    ("middleware.kafka.consumer-lag", "group"): "请输入消费组名称",
    ("middleware.mysql.connection-exhausted", "dsn"): "请输入数据库连接串（格式如 mysql://user@host:3306/db，可不带密码）",
    ("middleware.mysql.deadlock", "dsn"): "请输入数据库连接串（格式如 mysql://user@host:3306/db）",
    ("middleware.mysql.replication-broken", "dsn"): "请输入从库连接串（格式如 mysql://repl@host:3306/）",
    ("middleware.mysql.replication-lag", "dsn"): "请输入从库连接串（格式如 mysql://repl@host:3306/）",
    ("middleware.mysql.slow-query", "dsn"): "请输入实例连接串或标识（格式如 mysql://user@host:3306/db）",
    ("middleware.redis.bigkey", "addr"): "请输入 Redis 地址（格式如 127.0.0.1:6379）",
    ("middleware.redis.hotkey", "addr"): "请输入 Redis 地址（格式如 127.0.0.1:6379）",
    ("middleware.redis.memory-full", "addr"): "请输入 Redis 地址（格式如 127.0.0.1:6379）",
    # ---------- network ----------
    ("network.physical.interface-errors", "intf"): "请输入告警指向的网口名（如 eth0、ens192）",
    ("network.physical.optic-fault", "intf"): "请输入告警指向的网口名（如 eth0、xe-0/0/1）",
    ("network.reachability.mtu-blackhole", "dst"): "请输入目标地址（如 10.0.0.5 或某域名）",
    ("network.reachability.mtu-blackhole", "src"): "请输入源地址或出接口（如 192.168.1.10、eth0）",
    ("network.reachability.packet-loss", "dst"): "请输入目标地址（如 10.0.0.5 或某域名）",
    ("network.reachability.packet-loss", "src"): "请输入源地址或出接口（如 192.168.1.10、eth0）",
    ("network.routing.bgp-route-missing", "peer_ip"): "请输入 BGP 邻居的地址（如 10.0.0.1）",
    ("network.routing.bgp-route-missing", "prefix"): "请输入期望收到的前缀（如 10.20.0.0/16）",
    ("network.routing.bgp.neighbor-down", "peer_ip"): "请输入告警指向的 BGP 邻居地址（如 10.0.0.1）",
    ("network.routing.ospf-adjacency-stuck", "neighbor"): "请输入 OSPF 邻居的地址（如 10.0.0.2）",
    ("network.security-policy.acl-block", "flow"): "请描述被拦流量（五元组：源IP、源端口、目的IP、目的端口、协议，如 10.1.1.5 12345 10.2.2.8 443 tcp）",
    ("network.security-policy.acl-block", "intf"): "请输入涉及的接口名（如 eth0、ae0）",
    ("network.switching.stp-loop", "vlan_id"): "请输入疑似环路的 VLAN 编号（如 100）",
    ("network.switching.vlan-misconfig", "intf"): "请输入上行或接入接口名（如 eth0、ge-0/0/1）",
    ("network.switching.vlan-misconfig", "vlan_id"): "请输入涉及的 VLAN 编号（如 100）",
    ("network.traffic.anomaly-detect", "intf"): "请输入告警指向的网口名（如 eth0）",
    # ---------- obs ----------
    ("obs.alerting.alert-storm", "am_url"): "请输入 Alertmanager 地址（格式如 http://am.monitor:9093）",
    ("obs.alerting.false-positive", "prom_url"): "请输入 Prometheus 地址（格式如 http://prom:9090）",
    ("obs.alerting.false-positive", "alertname"): "请输入误报的告警名称",
    ("obs.metrics.missing", "prom_url"): "请输入 Prometheus 地址（格式如 http://prom:9090）",
    ("obs.metrics.missing", "metric"): "请输入查不到数据的指标名（如 node_cpu_seconds_total）",
    ("obs.metrics.target-down", "prom_url"): "请输入 Prometheus 地址（格式如 http://prom:9090）",
    ("obs.metrics.target-down", "target"): "请输入显示 down 的实例（格式如 10.0.0.5:9100）",
    ("obs.oncall.incident-timeline", "prom_url"): "请输入 Prometheus 或事件源地址（格式如 http://prom:9090）",
    ("obs.oncall.incident-timeline", "window"): "请输入事件时间范围（如 -2h..now 表示最近 2 小时）",
    # ---------- proc（结构化素材，输入的就是内容本身）----------
    ("proc.change.ticket-gen", "change_desc"): "请描述本次变更内容（做什么、为什么做）",
    ("proc.change.ticket-gen", "window"): "请输入变更窗口时间（如 2026-09-20 02:00-04:00）",
    ("proc.change.ticket-gen", "blast_radius"): "请描述变更影响面（涉及哪些系统/多少用户）",
    ("proc.change.ticket-gen", "rollback_plan"): "请描述回滚方案（出问题怎么退回）",
    ("proc.handover.shift-summary", "open_incidents"): "请输入未闭环的故障/工单清单（编号或一句话一项）",
    ("proc.handover.shift-summary", "pending_changes"): "请输入待执行/进行中的变更清单",
    ("proc.handover.shift-summary", "watch_items"): "请输入需要持续观察的事项",
    ("proc.incident.report-gen", "incident_summary"): "请用一句话概述本次故障",
    ("proc.incident.report-gen", "impact"): "请描述影响范围与时长（哪些业务、多久恢复）",
    ("proc.incident.report-gen", "root_cause"): "请输入已知的根因（尚未定位可直接回车）",
    ("proc.incident.report-gen", "timeline_ref"): "请输入时间线来源（聊天记录链接/工单号/文档路径）",
    # ---------- sec ----------
    ("sec.access.abnormal-login", "host"): "请输入需要排查的主机地址",
    ("sec.access.bruteforce", "host"): "请输入需要排查的主机地址",
    ("sec.access.abnormal-login", "window"): "请输入排查的时间范围（如 -24h..now 表示最近 24 小时）",
    ("sec.access.bruteforce", "window"): "请输入排查的时间范围（如 -24h..now 表示最近 24 小时）",
    ("sec.cert.expiry-inventory", "inventory"): "请输入证书清单文件路径（每行一个域名或 host:port）",
    ("sec.tls.cert-expiry", "endpoint"): "请输入待检测的地址和端口（如 example.com:443）",
    ("sec.vuln.scan-triage", "report"): "请输入扫描报告文件路径（trivy/grype 等的 JSON 输出）",
    # ---------- aicomp ----------
    ("aicomp.collective.nccl-allreduce-slow", "host"): "请输入需要排查的节点地址",
    ("aicomp.collective.nccl-allreduce-slow", "ngpus"): "请输入参与通信的 GPU 数（如 8）",
    ("aicomp.collective.nccl-allreduce-slow", "expected_busbw"): "请输入期望的 busbw（GB/s，如 180）",
    ("aicomp.collective.nccl-hang", "host"): "请输入需要排查的节点地址",
    ("aicomp.collective.nccl-hang", "job"): "请输入训练任务标识",
    ("aicomp.fabric.ib-link-down", "host"): "请输入需要排查的节点地址",
    ("aicomp.fabric.ib-link-down", "hca_port"): "请输入网卡端口号（InfiniBand HCA 端口编号，如 1）",
    ("aicomp.gpu.ecc-error", "host"): "请输入需要排查的节点地址",
    ("aicomp.gpu.ecc-error", "gpu_id"): "请输入出错的 GPU 序号（如 3）",
    ("aicomp.gpu.fell-off-bus", "host"): "请输入需要排查的节点地址",
    ("aicomp.gpu.fell-off-bus", "expected_gpus"): "请输入这台机器应有的 GPU 数（如 8）",
    ("aicomp.gpu.thermal-throttle", "host"): "请输入需要排查的节点地址",
    ("aicomp.gpu.thermal-throttle", "gpu_id"): "请输入限频的 GPU 序号（如 0）",
    ("aicomp.gpu.xid-error", "host"): "请输入出错节点地址",
    ("aicomp.gpu.xid-error", "gpu_id"): "请输入报错的 GPU 序号（如 3）",
    ("aicomp.training.gpu-util-low", "host"): "请输入需要排查的节点地址",
    ("aicomp.training.gpu-util-low", "pid"): "请输入训练进程号（如 12345）",
    ("aicomp.training.job-hang", "host"): "请输入需要排查的节点地址",
    ("aicomp.training.job-hang", "pid"): "请输入训练进程号（如 12345）",
    ("aicomp.training.slow-node", "job"): "请输入训练任务标识",
}
